### ISSUE TITLE
WMM model outdated

### ISSUE THREAD

**Issue by baolinliu** [cmweiss/geomag#10]
so I've used the software and it's great.  but looks like you are using WMM 2010, theres a 2015 one I'm using from here.

https://www.orekit.org/projects/orekit/repository/changes/src/test/resources/earth/WMM2015.COF?rev=ed8f9adf98ad60ac813998fc2b90d872846389c8

**Comment by cmweiss** [comment]
The WMM.COF is the current 2015 model released on December 15, 2014. See the header line here:
https://github.com/cmweiss/geomag/blob/master/geomag/geomag/WMM.COF

**Comment by baolinliu** [comment]
Thanks, I feel silly now.
